site_name: PYBOSSA Documentation
theme: 'material'
# theme: 'readthedocs'
markdown_extensions:
    - admonition
    - smarty
    - wikilinks
    # - urlize # requires: pip install git+https://github.com/r0wb0t/markdown-urlize.git
site_favicon: 'images/favicon.icon'
extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'
  font:
      text: 'Source Sans Pro'
  social:
    - type: 'github'
      link: 'https://github.com/Scifabric'
    - type: 'twitter'
      link: 'https://twitter.com/Scifabric'
repo_name: 'Scifabric/pybossa'
repo_url: 'https://github.com/Scifabric/pybossa'
copyright: 'Copyright © 2017 <a href="https://scifabric.com">Scifabric</a>'
google_analytics:
  - 'UA-49052879-1'
  - 'auto'
