site_name: PYBOSSA Documentation
theme: 'material'
# theme: 'readthedocs'
markdown_extensions:
    - toc(permalink=true)
    - admonition
    - smarty
    - wikilinks
    - codehilite(linenums=true)
    # - urlize # requires: pip install git+https://github.com/r0wb0t/markdown-urlize.git
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
site_favicon: 'images/favicon.icon'
extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'
  font:
      text: 'Source Sans Pro'
  social:
    - type: 'github'
      link: 'https://github.com/Scifabric'
    - type: 'twitter'
      link: 'https://twitter.com/Scifabric'
repo_name: 'Scifabric/pybossa'
repo_url: 'https://github.com/Scifabric/pybossa'
copyright: 'Copyright © 2017 <a href="https://scifabric.com">Scifabric</a>'
google_analytics:
  - 'UA-49052879-1'
  - 'auto'
pages:
  - Home: 'index.md'
  - Installation:
      - 'Getting started': 'installation/gettingstarted.md'
      - 'Installing the server': 'installation/guide.md'
      - 'Configuring PYBOSSA': 'installation/configuration.md'
      - 'Deploying PYBOSSA with Nginx and uWsgi': 'installation/deployment.md'
      - 'Administrating PYBOSSA': 'installation/admin.md'
      - 'Testing PYBOSSA with Vagrant': 'installation/vagrant.md'
  - Building a project:
      - 'Introduction': 'build/intro.md'
      - 'Quickstart: Creating a project': 'build/overview.md'
      - 'Using the command line': 'build/pbs.md'
      - 'Project tutorial': 'build/tutorial.md'
      - 'Configuring the project': 'build/project_settings.md'
      - 'RESTful API': 'build/api.md'
      - 'Domain model': 'build/model.md'
  - Testing PYBOSSA with Vagrant: 'installation/vagrant.md'
  - Contributing:
      - 'General':  'contributing.md'
      - 'Translating PYBOSSA': 'translating.md'
      - 'Writing plugins': 'plugins.md'
  - FAQ: 'faq.md'
